# Generated by Django 4.0.6 on 2022-08-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
