# Generated by Django 4.0.6 on 2022-08-25 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0002_alter_fundraiser_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='category',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundraisers', to='fundraiser.category'),
        ),
    ]
