# Generated by Django 4.0.6 on 2022-08-26 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundraiser', '0003_remove_fundraiser_category_fundraiser_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='donators',
            field=models.ManyToManyField(blank=True, related_name='donated_fundraisers', to=settings.AUTH_USER_MODEL),
        ),
    ]
