# Generated by Django 4.0.6 on 2022-07-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
