# Generated by Django 4.0.6 on 2022-08-10 22:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petition', '0004_comment_published'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('author', 'petition')},
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together={('author', 'petition')},
        ),
    ]
