# Generated by Django 4.0.6 on 2022-08-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0005_alter_comment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set(),
        ),
    ]
