# Generated by Django 4.0.6 on 2022-08-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0002_topic_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='countries_allowed',
            field=models.CharField(default='Worldwide', max_length=255),
        ),
    ]
