# Generated by Django 4.0.6 on 2022-08-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
