# Generated by Django 4.0.6 on 2022-08-17 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0005_alter_event_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='event',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='arrangements',
            new_name='requirements',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='participant_profile',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='event',
            name='countries_allowed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='street',
        ),
        migrations.RemoveField(
            model_name='event',
            name='training',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FileField(default='image.png', upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='when',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='event',
            name='cause',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='volunteering.cause'),
        ),
    ]
