# Generated by Django 4.0.6 on 2022-08-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0006_cause_remove_topic_event_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='volunteering.cause'),
        ),
    ]
