# Generated by Django 4.0.6 on 2022-08-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0007_event_organization_alter_event_cause'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cause',
        ),
        migrations.AddField(
            model_name='event',
            name='cause',
            field=models.ManyToManyField(related_name='events', to='volunteering.cause'),
        ),
    ]
