# Generated by Django 4.0.6 on 2022-08-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0008_remove_event_cause_event_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='skills',
        ),
        migrations.AddField(
            model_name='event',
            name='skills',
            field=models.ManyToManyField(related_name='skill_events', to='volunteering.skill'),
        ),
    ]
