# Generated by Django 4.0.6 on 2022-08-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0009_skill_remove_event_skills_event_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='goodfor',
            field=models.ManyToManyField(related_name='profile_events', to='volunteering.profile'),
        ),
    ]
