# Generated by Django 4.0.6 on 2022-08-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0010_profile_event_goodfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='apply',
            field=models.URLField(blank=True, null=True),
        ),
    ]
