# Generated by Django 4.0.6 on 2022-08-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0012_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
